rwname = {
  1: "Tony Stark",
  2: "Steve Rogers",
  3: "Wanda Maximoff",
  4: "Robert Bruce Banner",
  5: "Thor Odinson",
  6:"Bucky Burns",
  7:"Hank Pym",
  8:"Wasp",
  9:"Hawkeye",
  10:"Quicksilver",
  11:"Cressida ",
  12:"Swordsman",
  13:"Black Panther",
  14:"Vision",
  15:"Black Knight",
  16:"Black Widow",
  17:"Mantis",
  18:"Captain Marvel",
  19:"Falcon",
  20:"She-Hulk",
  21:"Spectrum",
  22: "Starfox",
  23: "War Machine",
  24: "Mockingbird",
  25: "Moira Brandon",
  26:"Firebird",
  27:"Thing",
  28:"Moon Knight",
  29:"Human Torch",
  30:"U.S.Agent",
  31:"Lightning ",
  32:"Madame Web",
  33:"Machine Man",
  34:"Darkhawk",
  35:"Ant-Man",
  36:"Mister Fantastic",
  37:"Invisible Woman",
  38:"Big Bertha",
  39:"Deadpool",
  40:"Mr. Immortal",
  41:"Deadpool",
}

